version: '3'
services:
  web:
    image: danwakeem/nodetest:latest
    command: ["npm", "start"]
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:3000"
    networks:
      - webnet
  cloudant:
    build:
      context: .
    image: ibmcom/cloudant-developer:latest
    container_name: cloudant-developer
    hostname: cloudant
    restart: always
    privileged: true
    volumes:
      - cloudant-developer:/srv
    network_mode: bridge
    networks:
      - webnet
networks:
  webnet:
volumes:
  cloudant-developer:
